title: Lulu Chen
subtitle: A Ph.D. Student in Fudan University
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: chenlulu.png
author: Lulu Chen
author_bio: Hi, my name is Lulu Chen. I am interested in Cloud computing, Edge computing, Distribute system and Machine Learning.
author_email: "llchen18@fudan.edu.cn"
author_location: Shanghai, China
author_website_url: "https://cll24.github.io"
typewrite-text: Nice to meet you.

author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_paper_details:
              - papers_title: 1.IoT microservice deployment in edge-cloud hybrid environment using reinforcement learning
                papers_description: We use RL to make service depolement strategy in edge-cloud hybrid environment.(Accepted)
                papers_url: https://ieeexplore.ieee.org/document/9162056
                visibility: true
              - papers_title: 2.An Adaptive Mechanism for Dynamically Collaborating Service Deployment and Task Scheduling in Edge Environment.
                papers_description: We design a mechanism to deploy service and schedule task.(Submitted)
                papers_url: https://www.baidu.com
                visibility: true

author_education_details:
              - college_logo: fdu.png
                college_name: Fudan University
                college_url: https://www.fudan.edu.cn
                college_degree: Ph.D. candidate
                description: Computer Science
                visibility: true
              - college_logo: uestc.png
                college_name: University of Electricity and Science Technology of China
                college_url: https://www.uestc.edu.cn
                college_degree: B.D.
                description: Applied Physicis
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
# github_username:  sujaykundu777
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
#show_author_work_experiences: true
show_author_education_details: true
show_author_paper_details: true
#show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
